apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  name: traefik
  namespace: infra
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.17.2
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  name: traefik-internal
  namespace: infra
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.17.3
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app: traefik-internal
