apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-redirect
  namespace: infra
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik.k8s.elee.cloud`)
    kind: Rule
    services:
    - name: traefik
      port: 8080

    middlewares:
      - name: redirect-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-https
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`traefik.k8s.elee.cloud`)
    kind: Rule
    services:
    - name: traefik
      port: 8080
  tls:
    certResolver: namecheap
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: infra
spec:
  redirectScheme:
    permanent: true
    scheme: https
