apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: kube-system
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer